apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: default
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.secret.apps: "logconfig"
data:
  application-kubernetes.properties: |
    my.custom.property: "22222222"
